"""empty message

Revision ID: 3fd5f68c2ce1
Revises: dd38628dd3e9
Create Date: 2026-08-05 18:33:22.207136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3fd5f68c2ce1'
down_revision: Union[str, Sequence[str], None] = 'dd38628dd3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'default_user'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('session_id')
        batch_op.drop_column('type')
        batch_op.drop_column('amount')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
