"""empty message

Revision ID: dd38628dd3e9
Revises: 7c0b2dfe05a5
Create Date: 2026-07-01 21:48:07.284622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dd38628dd3e9'
down_revision: Union[str, Sequence[str], None] = '7c0b2dfe05a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('session_id')
        batch_op.drop_column('amount')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
